#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &
${HOME}/.config/polybar/launch.sh &
nitrogen --restore &
# xinput set-prop 'Synaptics TM3053-004' 'libinput Tapping Enabled' 1 &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width 3
bspc config window_gap 5
bspc config focused_border_color '#DCA561'
# bspc config normal_border_color '#808080'

bspc config pointer_action1 move

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config leaf_monocle true
bspc config single_monocle true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a firefox desktop='^8' state=tiled follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=pseudo_tiled follow=off
bspc rule -a 'Confirm to replace files' state=floating follow=off
bspc rule -a 'File Operation Progress' state=floating follow=off
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Spotify desktop='^8' follow=on
bspc rule -a Okular state=floating follow=on
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Connman-gtk state=floating follow=on
bspc rule -a file-roller state=floating follow=on
