alias zshrc='${EDITOR} ~/.zshrc'
alias aliasconf='${EDITOR} ${ZSH_CUSTOM}/aliases.zsh'
alias pathconf='${EDITOR} ${ZSH_CUSTOM}/path.zsh'
alias vrc='${EDITOR} ${HOME}/.config/nvim'
alias sxhkdrc='${EDITOR} ${HOME}/.config/sxhkd/sxhkdrc'
alias bspwmrc='${EDITOR} ${HOME}/.config/bspwm/bspwmrc'
alias zimrc='${EDITOR} ${XDG_CONFIG_HOME}/zim/zimrc'
alias spectrconf='${EDITOR} ${XDG_CONFIG_HOME}/spectrwm/spectrwm.conf'
alias pkexec='pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY'

alias ls='eza --icons=always --group'
alias la='ls -a'
alias lt='ls -T'
alias lat='ls -aT'
alias ll='ls -lh --links --inode'
alias lah='ls -lah --links --inode'
alias man='batman'

alias gcc='gcc -Wall -Wextra -Wshadow -Wcast-align -Wconversion -Wuninitialized -Winit-self -fsanitize={address,undefined}'
alias g++='g++ -Wall -Wextra -Wshadow -Wcast-align -Wconversion -Wuninitialized -Winit-self -fsanitize={address,undefined}'

alias glog='git log --oneline --decorate --all --graph'

alias dsf='diff-so-fancy'
alias cls='clear'
alias srczsh='exec zsh'
alias vbox-modprobe='sudo modprobe vboxdrv'

alias hx='helix'
alias nv='nvim'
alias bt='bluetoothctl'
alias lg='lazygit'
